# Draft outfitter candidates (Claude research, UNVERIFIED except peremarquette/pine-mi which user confirmed).
# (name, website_or_blank, town, services, note)
CAND = {
 # WI
 "kickapoo":[("Drifty's Canoe Rental","","Ontario, WI","canoe/kayak, shuttle","Landing 1 area"),
             ("Mr. Duck's Canoe Rental","","Ontario, WI","canoe/kayak, shuttle",""),
             ("Titanic Canoe Rental","","Ontario, WI","canoe/kayak, shuttle","")],
 "wolf-upper":[("Bear Paw Outdoor Adventure Resort","https://bearpawoutdoors.com","White Lake, WI","kayak/raft, shuttle, lodging","Sections II-III"),
               ("Shotgun Eddy Rafting","https://shotguneddy.com","White Lake, WI","rafts, shuttle","whitewater rafting")],
 "black":[("Lost Falls Resort","https://www.lostfalls.com","Black River Falls, WI","canoe/kayak/tube, camping","confirmed livery in earlier research")],
 "crystal":[("Ding's Dock","https://dingsdock.com","Waupaca, WI","canoe/kayak, shuttle","Crystal River trips")],
 "mecan":[("Mecan River Outfitters & Lodge","https://mecanriveroutfitters.com","Princeton, WI","canoe/kayak, shuttle","")],
 "yahara":[("Rutabaga Paddlesports","https://rutabaga.com","Madison, WI","kayak rental/sales","shop rentals, not a livery")],
 "milwaukee":[("Milwaukee Kayak Company","https://milwaukeekayak.com","Milwaukee, WI","kayak/SUP","urban river only")],
 "sugar":[("Sweet Minihaha Campground","","Brodhead, WI","canoe/kayak, camping","")],
 # IL
 "vermilion-il":[("Vermillion River Rafting","https://www.vermillionriverrafting.com","Oglesby, IL","rafts/kayak, shuttle","May-mid-July season")],
 "mfvermilion":[("Kickapoo Adventures","","Oakwood, IL (Kickapoo SRA)","canoe/kayak, shuttle","")],
 "kishwaukee":[("Rocktown Adventures","https://rocktownadventures.com","Rockford, IL","kayak, shuttle","")],
 "fox-il2":[("C&M Canoe Rental","","Wedron, IL","canoe/kayak, shuttle","Ayers Landing area"),
            ("Ayers Landing","","Wedron, IL","launch, rentals","private, fee")],
 "dupage":[("Naperville Kayak","https://napervillekayak.com","Naperville, IL","kayak, shuttle","")],
 "kankakee":[("Reed's Canoe Trips","https://reedscanoetrips.com","Kankakee, IL","canoe/kayak, shuttle","")],
 "cache-il":[("Cache Bayou Outfitters","","Ullin, IL","kayak, guided swamp tours","")],
 # MI (peremarquette + pine-mi confirmed already in map)
 "peremarquette":[("Baldwin Canoe Rental","https://baldwincanoe.com/pere-marquette-river/","Baldwin, MI","canoe/kayak, shuttle","CONFIRMED by user"),
                  ("Henry's Landing","http://www.henryslanding.com/kayak-rental.html","Custer/Scottville, MI","canoe/kayak, camping","CONFIRMED by user"),
                  ("Ivan's Canoe Rental","https://ivansmichigan.com/","Baldwin, MI","canoe/kayak, camping","CONFIRMED by user")],
 "pine-mi":[("Pine River Paddlesports Center","https://www.thepineriver.com/pine-river","Wellston, MI","canoe/kayak, shuttle, camping","CONFIRMED by user"),
            ("Horina's Canoe & Kayak Rental","https://www.horinasprcanoe.com/thepineriver","Wellston, MI","canoe/kayak, shuttle","CONFIRMED by user"),
            ("The Sportsman's Port","https://www.thesportsmansport.com/","Wellston, MI","canoe/kayak, camping","CONFIRMED by user")],
 "ausable":[("Carlisle Canoe Livery","https://carlislecanoes.com","Grayling, MI","canoe/kayak, shuttle",""),
            ("Penrod's AuSable River Resort","","Grayling, MI","canoe/kayak, cabins",""),
            ("Borchers AuSable Canoeing","https://canoeborchers.com","Grayling, MI","canoe/kayak, B&B","")],
 "rifle":[("Russell Canoe Livery","https://russellcanoe.com","Omer, MI","canoe/kayak/tube, camping",""),
          ("White's Canoe Livery","","Sterling, MI","canoe/kayak/tube","")],
 "sturgeon-mi":[("Big Bear Adventures","https://bigbearadventures.com","Indian River, MI","kayak/raft/tube, shuttle","")],
 "platte-mi":[("Riverside Canoe Trips","https://canoemichigan.com","Honor, MI","canoe/kayak/tube","at M-22 bridge")],
 "betsie":[("Betsie River Canoes & Campground","","Thompsonville, MI","canoe/kayak, camping","")],
 "boardman":[("Ranch Rudolf","https://ranchrudolf.com","Traverse City, MI","canoe/kayak/tube, lodging",""),
             ("The River Outfitters","","Traverse City, MI","kayak/SUP","lower river/Boardman Lake")],
 "jordan-mi":[("Jordan Valley Outfitters","https://www.jvoutfitters.com","East Jordan, MI","canoe/kayak/tube, shuttle","URL from earlier research"),
              ("Swiss Hideaway","","Mancelona, MI","canoe/kayak, shuttle","Graves Crossing")],
 "white-mi":[("Happy Mohawk Canoe Livery","https://happymohawk.com","Montague, MI","canoe/kayak/tube","from earlier research")],
 "rogue":[("AAA Rogue River Canoe Rental","","Rockford, MI","canoe/kayak","")],
 "manistee-upper":[("Chippewa Landing","https://chippewalanding.com","Manton, MI","canoe/kayak, camping, shuttle",""),
                   ("Smithville Landing","","Lake City, MI","canoe/kayak, shuttle","")],
 "huron-mi":[("Skip's Huron River Canoe Livery","","Dexter, MI","canoe/kayak, shuttle",""),
             ("Argo Park Canoe & Kayak (City of Ann Arbor)","","Ann Arbor, MI","kayak, Argo Cascades","")],
 "chippewa-mi":[("Chippewa River Outfitters","https://chippewariveroutfitters.com","Mt. Pleasant, MI","kayak/tube, shuttle","")],
 "cass":[("Frankenmuth Kayak Adventures","","Frankenmuth, MI","kayak, shuttle","")],
 # KY
 "elkhorn":[("Canoe Kentucky","https://canoeky.com","Frankfort, KY","canoe/kayak, shuttle","the Elkhorn institution")],
 "red-ky":[("Red River Adventure","","Slade, KY","canoe/kayak, shuttle","")],
 "green-ky":[("Green River Canoeing (Mammoth Cave)","","Brownsville, KY","canoe/kayak, shuttle","park stretch")],
 "rockcastle":[("Rockcastle Adventures","","Livingston, KY","canoe/kayak","")],
 "licking-ky":[("Thaxton's Canoe Trails","","Butler, KY","canoe/kayak","NOTE: lower Licking, outside mapped stretch")],
 "floydsfork":[("Blue Moon Canoe & Kayak of Kentucky","","Louisville, KY","kayak, shuttle","Parklands trips")],
 # WV
 "greenbrier":[("Greenbrier River Campground & Outfitters","https://greenbrierrivercampground.com","Alderson, WV","kayak/tube, camping, shuttle","")],
 "sbpotomac":[("Eagle's Nest Outfitters","","Petersburg, WV","canoe/kayak, shuttle","Trough trips")],
 "cheat":[("Blackwater Outdoor Adventures","","St. George, WV","canoe/kayak, shuttle","upper Cheat"),
          ("Cheat River Outfitters","https://cheatriveroutfitters.com","Albright, WV","rafts, whitewater","canyon = advanced")],
 "coal-wv":[("Coal River Group Paddle Shack","https://coalrivergroup.com","Tornado, WV","kayak, water trail","")],
 # OH
 "mohican":[("Mohican Adventures","https://mohicanadventures.com","Loudonville, OH","canoe/kayak/tube, camping",""),
            ("Loudonville Canoe Livery","","Loudonville, OH","canoe/kayak","")],
 "littlemiami":[("Morgan's Outdoor Adventures","https://morgancanoe.com","Fort Ancient, OH","canoe/kayak/raft",""),
                ("Loveland Canoe & Kayak","https://lovelandcanoe.com","Loveland, OH","canoe/kayak, shuttle","")],
 "bigdarby":[("Trapper John's Canoe Livery","","Grove City, OH","canoe/kayak","")],
 "mad-oh":[("Birch Bark Canoe Livery","","Springfield, OH","canoe/kayak","")],
 "cuyahoga":[("Burning River Adventures","https://burningriveradventures.com","Valley View, OH","kayak, shuttle","")],
 # MN
 "cannon":[("Cannon Falls Canoe & Bike Rental","","Cannon Falls, MN","canoe/kayak/tube, shuttle",""),
           ("Welch Mill Canoeing & Tubing","https://welchmillcanoeandtube.com","Welch, MN","canoe/kayak/tube","")],
 "root-mn":[("Root River Outfitters","https://rootriveroutfitters.com","Lanesboro, MN","canoe/kayak/tube, shuttle",""),
            ("Little River General Store","","Lanesboro, MN","kayak/bike rental","")],
 "missheadwaters":[("Itasca Sports","https://itascasports.com","Itasca State Park, MN","kayak/canoe rental","headwaters")],
 # IN
 "sugarcreek":[("Clements Canoes","https://clementscanoes.com","Crawfordsville, IN","canoe/kayak, shuttle",""),
               ("Sugar Valley Canoe Trips","","Marshall, IN","canoe/kayak","Turkey Run")],
 "tippecanoe":[("Riverside Rentals","","Winamac, IN","canoe/kayak/tube","")],
 "blue-in":[("Cave Country Canoes","https://cavecountrycanoes.com","Milltown, IN","canoe/kayak, shuttle","")],
 "whitewater-in":[("Whitewater Canoe Rental","","Brookville, IN","canoe/kayak/tube","")],
 "flatrock-in":[("Blues Canoes","https://bluescanoes.com","Edinburgh, IN","canoe/kayak, shuttle","")],
 "driftwood":[("Blues Canoes","https://bluescanoes.com","Edinburgh, IN","canoe/kayak, shuttle","same livery as Flatrock")],
 # IA
 "upperiowa":[("Chimney Rock Canoe Rental & Campground","","Cresco, IA","canoe/kayak, camping, shuttle",""),
              ("Randy's Bluffton Store & Campground","","Bluffton, IA","canoe/kayak, camping","")],
 "boone-ia":[("Seven Oaks Recreation","https://sevenoaksrec.com","Boone, IA","kayak/tube, shuttle","")],
 # MO
 "current":[("Akers Ferry Canoe Rental","https://currentrivercanoe.com","Salem, MO","canoe/kayak/raft, shuttle",""),
            ("Jadwin Canoe Rental","https://jadwincanoe.com","Jadwin, MO","canoe/kayak, shuttle",""),
            ("Carr's Canoe Rental","","Round Spring, MO","canoe/kayak","")],
 "jacksfork":[("Harvey's Alley Spring Canoe Rental","","Eminence, MO","canoe/kayak, shuttle",""),
              ("Windy's Canoe Rental","https://windyscanoe.com","Eminence, MO","canoe/kayak, shuttle","")],
 "elevenpoint":[("Hufstedler's Canoe Rental","","Riverton, MO","canoe/kayak, shuttle",""),
                ("Richards Canoe Rental","","Alton, MO","canoe/kayak","")],
 "niangua":[("Niangua River Oasis","https://nianguariveroasis.com","Lebanon, MO","canoe/kayak/raft, camping","")],
 "meramec":[("Ozark Outdoors Riverfront Resort","https://ozarkoutdoors.net","Leasburg, MO","canoe/kayak/raft, camping","")],
 "gasconade":[("Gasconade Hills Resort","https://gasconadehills.com","Richland, MO","canoe/kayak/raft, cabins","")],
 "bigpiney":[("Rich's Last Resort","","Licking, MO","canoe/kayak, camping","")],
 "huzzah":[("Huzzah Valley Resort","https://huzzahvalley.com","Steelville, MO","canoe/kayak/raft/tube, camping",""),
           ("Bass' River Resort","https://bassresort.com","Steelville, MO","canoe/kayak/raft/tube, camping","")],
 "northfork-mo":[("Twin Bridges Canoe & Campground","https://twinbridgescanoe.com","West Plains, MO","canoe/kayak, camping, shuttle",""),
                 ("Sunburst Ranch","","Caulfield, MO","canoe/kayak, camping","")],
}

# --- v8 additions (new rivers qualified by known outfitters; all draft/unverified) ---
CAND.update({
 "flambeau":[("Flambeau River Lodge","","Ladysmith, WI","canoe/kayak, lodging","N Fork trips")],
 "namekagon":[("Jack's Canoe Rental","","Trego, WI","canoe/kayak, shuttle","Namekagon/St. Croix Riverway"),
              ("Pardun's Canoe Rental","","Danbury, WI","canoe/kayak, shuttle","")],
 "peshtigo":[("Kosir's Rapid Rafts","https://kosirs.com","Silver Cliff, WI","rafts/kayak, camping","Roaring Rapids"),
             ("Thornton's Whitewater Rafting Resort","","Athelstane, WI","rafts, camping","")],
 "brule":[("Brule River Canoe Rental","","Brule, WI","canoe/kayak, shuttle","Bois Brule")],
 "nbchicago":[("Chicago River Canoe & Kayak","","Chicago/Skokie, IL","kayak, shuttle","N Branch water trail")],
 "thornapple":[("U-Rent-Em Canoe Livery","","Hastings, MI","canoe/kayak/tube","")],
 "flat":[("Double R Ranch Resort","https://doublerranch.com","Smyrna, MI","canoe/kayak/tube","")],
 "pawpaw":[("Third Coast Paddling","https://thirdcoastpaddling.com","Watervliet, MI","kayak, shuttle","")],
 "dowagiac":[("Doe-Wah-Jack's Canoe Rental","","Niles, MI","canoe/kayak, shuttle","")],
 "clinton":[("Clinton River Canoe & Kayak","","Sterling Heights, MI","canoe/kayak, shuttle","")],
})
